### ISSUE TITLE
document validator needs controlled vocabulary option for some fields

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#146]
I merged the branches! Nice job! Thanks!

There's a new branch document_validator_2 for continued work.

**Comment by stevevanhooser** [comment]
OK, I added

ndi_common/controlled_vocabulary/GenBankControlledVocabulary.tsv.gz

which has the controlled vocabulary for the forthcoming ndi_document_subject_animal document.

The animal Scientific_Name will have to exactly match the GenBank Scientific Name (given in the first column of the tab-separated value file). The Common_name will have to exactly match the GenBank Common_name (the second column).

If someone uses a synonym for the scientific name (third column, entries separated by a comma and space ', ' and then a tab), then it should be an error but suggest the GenBank scientific name. The 4th columns is other common names, also separated with a ', ' and ending with a newline.

The file is gzipped right now. On the first calling, it could be gunzipped (Matlab function 'gunzip') into a temporary directory for easier searching. It is easy to search in place in .gz form via unix on MacOS or Linux with the unix command zgrep but I suppose we can't count on that function being present on Windows machines (or perhaps even all Macs).

If there is a better format, we can convert. It is 29MB in its present form when unzipped.

Thanks
Steve

**Comment by zhaoy17** [comment]
I think if we want certain field to have the exact match of the set of vocabulary in the first column, the easiest way to do is that we can store all the list of vocabulary in a single json schema file using enum keyword to store the set of all all accepted vocabulary and then simply refer to that json schema file for the field that we want its set of values to be an exact match as the ones listed in the schema file. The search should be efficient, as I think the Java schema validator would converts those set of vocabulary into a HashSet and can easily tell if the word the user has entered matches with an vocabulary in the HashSet. This approach, however, won't allow us to have more complex validation like throwing an error suggesting the user to GenBank scientific name when they enter the a synonym. I think one way of resolving that is that we can modify the java implementation of the json schema validator a little bit by allowing it recognize our own customized tag in our json schema (like "animal_name"), which is not a part of the json schema official specification. I read through a parts of the source code of in the original Java implementation (https://github.com/everit-org/json-schema/tree/master/core/src/main/java/org/everit/json/schema/internal), it seems like we can extends the FormatValidator interface (https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/FormatValidator.java) and create our own customized json format tag like (type: "string", format: "animal-subject") and validate it in the way we want to validator to valdiate. We can store the list of vocabulary into a key-value pairs HashMap in Java (this can actually be serialized in Java into a specific file format, and we can load the file quite fast every time we need it), which allow us to quickly identify the matches of the synonym. Alternatively, we can do the validation logic of those specific field in MATLAB, but we have to be careful to skip those field when we pass it to our Java validator since it would throws an error if it find json schema containing keywords it doesn't recognize. I think the downside for the Java approach would be that every time we want to make changes to the implementation, we might have to recompile it and update the jar file as oppose to simply changing the code.  The advantage of the Java approach would be that we have a validator that naturally recognizes our customized format and know how to throw an error in the specific way we want. The downside of the MATLAB approach would be that we have parse the json schema in MATLAB first to split the job of verifying out customized tag (like animal-subject) from the other tags which needs to be done by Java. This can create more work than necessary when validating the json schema, and it could be a bit bug-prone if we didn't split the work properly. Also I'm not quite sure how fast MATLAB is at searching through the list of word (or we still have to rely on calling Java.util.HashMap in MATLAB to do the work of validating the vocabulary). The advantage would be that we can modify the MATLAB file and see the effects without having to recompile the Java file. I guess we can try both approaches to see which one works the best. 

Thanks,

Peter Zhao

**Comment by stevevanhooser** [comment]
Hi Peter - 

I think Java is probably the better way to go compared to Matlab

Regarding the implementation, is there a way to make a tag that is not an "animal-subject" but something like "hashfile://fullpathtohashfile/scientific_name" so that the code does not need to be recompiled anywhere? In other words, the schema information would be an instruction rather than a type. One could make "hashfile://pathtofullhashfile/genbank_common_name%20match@20scientific_name" or something like that to indicate correspondence?? I don't know, I'm just trying to think of a way to put it all in the schema and have the code be invariant.

Thanks
Steve

**Comment by zhaoy17** [comment]
Hi professor,

I was thinking that instead of specifying them within the JSON schema document, we can perhaps allow the user to specify a certain set of configuration or instructions (like the path to the text file we want the validator to look at, or other options) in MATLAB before running ndi_validate, and ndi_validate would pass that information to com.ndi.validator. Putting those instruction in the json-document might be possible, but I think doing so in the JSON schema document would require making changes to everit-org's json validator's internal JSON parser (implemented in this series of classes that the SchemaLoader class use: https://github.com/everit-org/json-schema/tree/master/core/src/main/java/org/everit/json/schema/loader), which has a quite complicated code structure and it might take some time to understand it. We could also break the validator if not done properly. I think it would be easier to have say AnimalSubjectValidator that implements the FormatValidator interface, but has a constructor that allows user to pass in various set of instruction and then the Validator knows how to validate based on the user's instruction specify in MATLAB. I feel like this might be a better way to go without having to tampering too much with the original implementation. 

Thanks,
Peter

**Comment by stevevanhooser** [comment]
Sounds good to me. So the documents would have 2 schemas; one in JSON and then another that checked controlled vocabularies, so that we can focus on writing the second tool without altering the first. Sounds fine to me!

**Comment by stevevanhooser** [comment]
we essentially did this
