### ISSUE TITLE
Profiling functions in Tutorial 2.3

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#181]
I'd like to request a profile analysis of where our functions are spending a lot of time.

I don't have much experience with the Matlab profiler, but it is really useful. To use it, you can do the following:

```
profile on
% run the bit you want to analyze, such as the following
dirname = [userpath filesep 'Documents' filesep 'NDI' filesep 'ts_exper2']; % change this if you put the example somewhere else
ref = 'ts_exper2';
S = ndi.setup.vhlab(ref,dirname);  

% let's find our probes that correspond to extracellular electrodes
p = S.getprobes('type','n-trode');

% then check out the performance

profile viewer

% and save it to disk

profsave
```

I'd be interested in results of this function when the session has been run through the entire tutorials (that is, when the database has lots of entries), and when you run it right after S.database_clear('yes'). Where does the code spend a lot of time?

Thanks!
Steve

**Comment by stevevanhooser** [comment]
Check out this documentation: https://www.mathworks.com/help/matlab/ref/profile.html

**Comment by KellyZhangL** [comment]
I ran a profile analysis of all the functions (and I saved analysis reports of those that did not have instant output). Below are functions that took especially long:

**Tutorial 2.1**
`ndi.example.tutorial.plottreeshrewdata(my_smr_file);`
- total time: 13.307 s
- _read_SOMSMR_datafile_: time: 3.894 s, line 42 `header = ndr.format.ced.read_SOMSMR_header(filename);` takes 1.586 s

**Tutorial 2.2**
`p_ctx1_list = S.getprobes('name','ctx','reference',1)`
- total time: 11.074 s
- _dumbjsondb>dumbjsondb.read_: 3.321 s, line 230 takes 2.063 s
- _SONFileHeader_: 2.542 s, line 47 takes 2.454 s

`[data,t,timeref_p_ctx1]=p_ctx1.readtimeseries(epoch_to_read,-Inf,Inf);`
- total time: 8.884 s
- _SONFileHeader_: 4.449 s, line 47 takes 4.435 s


**Tutorial 2.3**
`se.extract(p{1},[],my_extraction_name{1},redo);`
- The first time I ran this, total time was 211.634 s. My computer forced restart due to some Windows issues so the results below are after the restart (noticeably less time).
- total time: 170.098 s
- _SONFileHeader_: 125.329 s, line 47 `Head.pad=fread(fid,52,'char=>char'); ` takes 122.575 s

`se.extract(p{2},[],my_extraction_name{2},redo);`
- same issues as above (original total run time was 234.680 s)
- total time: 212.393 s
- _SONFileHeader_: 159,408 s, line 47 takes 156.226 s

`spike_cluster_doc = ssa.spike_sort(p{1},my_extraction_name{1},my_sorting_name,redo)`
- total time: 101.479 s
- _centerspikes_neg_: 71.555 s, line 34 `centeredspikes = cat(1, centeredspikes, paddedspike);` takes 70.360 s
- _uiwait_: 25.501 s, line 81 `waitfor(...);` takes 22.465 s

`spike_cluster_doc = ssa.spike_sort(p{2},my_extraction_name{2},my_sorting_name,redo)`
- total time: 125.815 s
- _centerspikes_neg_: 106.891 s, line 34 takes 104.822 s


**Tutorial 2.4**
`[stim_pres_docs] = sapp.parse_stimuli(stimprobe,redo);`
- total time: 10.374 s
- _dumbjsondb>dumbjsondb.read_: 2.803 s, line 230 takes 1.740 s
- _dos_: 2.436 s, line 67 `[varargout{1:nargout}] = matlab.system.internal.executeCommand(varargin{:});` takes 2.434 s

`cs_doc = rapp.label_control_stimuli(stimprobe,redo);`
- total time: 7.410 s
- _dos_: 2.981 s, line 67 takes 2.979 s

`rdocs{1} = rapp.stimulus_responses(stimprobe, e{1}, redo);`
- initially took a total time of 21.556 s but reran everything due to a _rdocs = 1x1 cell_ error (in Discussion of Tutorial 2.4) and I'm now getting a total run time of 12 s

`for i=1:2,
    tdoc{i} = oapp.calculate_tuning_curve(e{i});
    oriprops{i} = oapp.calculate_all_oridir_indexes(e{i});
end;`
- total time: 130.383 s
- _otfit_carandini_err_: 89.095 s, line 42 `if ~exist('stddev'),` takes 66.132 s, line 40 `vlt.data.assign(varargin{:});` takes 9.301 s, line 52 `[Rsp,Rp,Op,sig,Rn]=vlt.fit.otfit_carandini_conv('TOREALFORFIT',par'varargin{:});` takes 11.767 s


**Tutorial 2.5**
- no noticeable issues; all functions ran at 2 seconds (max) or less (usually 0.4 s)


**Time consuming code that I've noticed in multiple profiles**
- _dumbjsondb>dumbjsondb.read_: line 230 `if exist([p f], 'file');`, line 231 `t = vlt.file.textfile2char([p f]);`
- centerspikes_neg_: line 34 `centeredspikes = cat(1, centeredspikes, paddedspike);` 
- _SONFileHeader_: line 47 `Head.pad=fread(fid,52,'char=>char'); `

**Comment by KellyZhangL** [comment]
Running `S.database_clear('yes');` and `clear;`

**Comment by stevevanhooser** [comment]
Really nice work!

It seems like `exist(filename,'file')` is really slow. We ought to replace it with something faster. Reading on the internet, it seems that `exist(filename,'file')` looks for a file that has the name `filename` anywhere on the path. But we really just want to know if that filename exists right where we are looking. 

There is a new function (introduced in Matlab 2017) called isfile(filename) that does that.

We could just replace our calls to `exist(filenname,'file')` with that. However, we have people who run older versions of Matlab.

Why don't you make a fork of vhlab-toolbox-matlab. You can remove the vhlab-toolbox-matlab that the installer installed and put your own in its place by being in a DOS shell, changing to that directory and writing with `git clone http://github.com/yourusername/vhlab-toolbox-matlab` and add a new function: `vlt.file.isfile.m`. See if you can figure out where to put that file so it is there in the package.

The code will be:

```
function b = isfile(filename)
% write some documentation..see if you can follow the form!


b = 0;
try,
  b=isfile(filename);
catch, % this is run if that function fails, for example, if there is no function called isfile in that version of Matlab
    try, 
        b = java.io.File(filename).exists;   % try calling java
    catch,
        b = exist(filename,'file'); % if we really have no other means, then use exist()
    end;
end;
```
   
 


Then, go to dumbjsondb>dumbjsondb.read (also in vhlab-toolbox-matlab) and replace `exist(filename,'file')` with `vlt.file.isfile(filename)`. We should get an amazing speed up.


When you have tested that it works, you can issue a pull request in GitHub so we can merge it back!

**Comment by KellyZhangL** [comment]
**Tutorial 2.3**
`se.extract(p{1},[],my_extraction_name{1},redo);`
- 173.635 s
- _SONFileHeader_: 127.340 s, line 47 takes 124.445 s

`se.extract(p{2},[],my_extraction_name{2},redo);`
- 220.571 s

`spike_cluster_doc = ssa.spike_sort(p{1},my_extraction_name{1},my_sorting_name,redo)`
- 129.358 s

`spike_cluster_doc = ssa.spike_sort(p{2},my_extraction_name{2},my_sorting_name,redo)`
- 103.923 s


**Tutorial 2.4**
`for i=1:2,
    tdoc{i} = oapp.calculate_tuning_curve(e{i});
    oriprops{i} = oapp.calculate_all_oridir_indexes(e{i});
end;`
- 88.991 s
- _otfit_carandini_err_: 62.226 s, line 42 `if ~exist('stddev'),` takes 46.668 s 

**Noticed this line of code as well:**
_dos_: line 67 `[varargout{1:nargout}] = matlab.system.internal.executeCommand(varargin{:});`


Overall, I noticed that after running `S.database_clear('yes');`, functions ran quicker and more smoothly (less issues). Since everything downloaded as Chrome HTML Documents, I'm happy to download and attach any files that you're interested in).

**Comment by stevevanhooser** [comment]
fixed in vhlab-toolbox-matlab!  Runs a lot faster now.
