### ISSUE TITLE
iodevice - rename to daqreader?

### ISSUE THREAD

**Issue by orarogovin** [VH-Lab/NDI-matlab#90]
Since the iodevices are not actually devices, but file readers, should they be renamed "daqreaders"? As is, it's hard to tell when we're talking about an iodevice versus a DAQ.

**Comment by nellh** [comment]
I like the iodevice name, at least if this [comment is correct](https://github.com/VH-Lab/NDI-matlab/blob/master/probe/ndi_probe.m#L7-L8) and it can represent stimulation devices as well. Are interactive acquisition devices also a possibility?

**Comment by stevevanhooser** [comment]
We had a meeting last week about this... It is true that probes can be a measurement device or a stimulation device. However, the way we use the objects that are called iodevices now is only to read information about what stimuli produced (that is acquired). So right now, we are only reading.

You raise a good question about whether interactive acquisition is a possibility. Right now we have avoided that because of the complexity. It may be possible in the far future. 

I guess the question is, does it help the naive user if it is called a reader because that is all they do now? 

A "reader" could be interactive or read from a file. But it wouldn't be a controller, if we wanted to add that down the road...feeling indecisive..any thoughts?

**Comment by stevevanhooser** [comment]
We decided to change ndi_iodevice to ndi_daqsystem. We had a long debate as to whether they were just readers, but we decided that in principle this object could be more than a reader. But it was confusing to many new undergrads on the project that the object could represent a system instead of just a simple proprietary daq (for example, our visual stimulation system is a homebuilt system that also requires using some daq channels on a proprietary daq). 

Now, each ndi_daqsystem object has an ndi_daqreader that reads the files associated with the daqsystem. There are only a few types of ndi_daqsystem objects (very general) and there is a different ndi_daqreader for each specific instance (there is one for different DAQs when used in a vanilla configuration, and one for our kludged stimulus system that reads from multiple DAQs as appropriate).
