### ISSUE TITLE
change dependencies of pm_hash to some other hash function

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#95]
Not everyone has Simscape toolbox, we can write our own hash function so it is easier

**Comment by stevevanhooser** [comment]
still stymied; tried a few of the functions on FileExchange but none can work with arbitrary objects

**Comment by stevevanhooser** [comment]
Idea: all NDI objects can have a hash function

Then write a hash function that calls a third-party like DataHash for all standard types and calls the hash function for each object

The overall hash is bitxor(item1,bitxor(item2,bitxor(item3,...)))

**Comment by ehennestad** [comment]
Regarding HashTable:

I tried to use this function instead of getting the SimScape toolbox. Although it does not officially work for objects, there is a line in the function that was commented out which, when turned on makes it work for objects as well.

This is the relevant piece of code. Unfortunately, it might only be a short term solution.

function DataBin = ConvertObject(DataObj)
% Convert a user-defined object to a binary stream. There cannot be a unique
% solution, so this part is left for the user...
 
try    % Perhaps a direct conversion is implemented:
   %DataBin = uint8(DataObj); % Comment out EH.2022-02-01
   
   % Matt Raum had this excellent idea - unfortunately this function is
   % undocumented and might not be supported in te future:
   DataBin = getByteStreamFromArray(DataObj); % Comment in EH.2022-02-01
   
catch  % Or perhaps this is better:
   WarnS   = warning('off', 'MATLAB:structOnObject');
   DataBin = struct(DataObj);
   warning(WarnS);
end
 
end

**Comment by ehennestad** [comment]
See also this post about the getByteStreamFromArray function:
https://undocumentedmatlab.com/articles/serializing-deserializing-matlab-data

**Comment by stevevanhooser** [comment]
Wow, what a find. I'll test it on Linux/Mac/Windows at home on my test machine and report back. The nice thing about pm_hash is that it works exactly the same on all platforms (provides the same hash) so if people are working on different machines, the hash is the same. 
Thanks!

**Comment by stevevanhooser** [comment]
Remarkable.

getByteStreamFromArray and getArrayFromByteStream send custom objects and regular matlab variables seamlessly across the following applications:

MacOS Matlab 2019a
MacOS Matlab 2021b
Linux Matlab 2021a
Windows Matlab 2021b

I used new files ndi.test.misc.bytestream.* to check it.
